### ISSUE TITLE
Acquiring Packlist

### ISSUE THREAD

**Issue by ikuria** [mac-reid/lazydcc#9]
hi, is "Acquiring Packlist" so important to download a pack? it runs forever in big chats, so is there an option to disable it, or remove this part from the code to directdownload? some use https://ixirc.com/ to search a pack and already know the packnumber, so you only need the download process

**Comment by mac-reid** [comment]
sure, I added an option. feel free to test it out and let me know if it doesn't work. for now, I'll close this.
